import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend } from "next/font/google";
import "@/app/styles/globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import ContactForm from "../components/ContactForm";
import Testimonials from "../components/Testimonials";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"]
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"]
});

const lexend = Lexend({
	variable: "--font-lexend",
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "SenasticAI - Your Partner in Talent",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth">
			<body
				className={`${lexend.variable} ${geistSans.variable} ${geistMono.variable} font-lexend antialiased min-h-screen text-slate-800`}
			>
				<Header />
				<div className="h-full">
					<main className="overflow-x-hidden">{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
